version: '3'

services:
  proxy:
    restart: always
    container_name: rethink_proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
     - ./domains:/domains
     - ./certs:/certs
     - ./logs:/var/log/nginx

  db:
    restart: always
    container_name: rethink_db
    environment:
        - POSTGRES_USER=##
        - POSTGRES_PASSWORD=##
        - PGDATA=/pgdata
    image: mdillon/postgis:9.6
    ports:
        - "5432:5432"
    volumes:
        - ./pgdata:/pgdata

  classificator_http:
    restart: always
    container_name: rethink_classificator_http
    build: ./dockerfiles/rethink_mora_classificator_http_server_docker
    ports:
       - "8080:80"

  django_app_web:
     restart: always
     container_name: rethink_webapp
     environment:
         - DB_ADDRESS=##
         - DB_PORT=##
         - DB_NAME=##
         - DB_USER=##
         - DB_PASSWORD=##
         - DB_HOST=db
     build: ./dockerfiles/rethink_django_webapp_docker
     #image: webapp
     volumes:
         - ./rethink_django_webapp:/home/docker/code/app
         - ./django_logs:/logs
         - ./rethink_django_webapp/static:/static
     ports:
         - "8000:80"

  pgadmin:
    restart: always
    container_name: rethink_pgadmin
    build: ./dockerfiles/pgadmin/
    environment:
        - POSTGRES_HOSTNAME=##
        - POSTGRES_HOST=##
        - POSTGRES_PORT=##
        - POSTGRES_DEFAULTDB=##
        - APACHE_SERVERNAME=pgadmin
    ports:
      - "6002:80"
    links:
      - db