# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=500)),
                ('lat', models.CharField(default=0.0, max_length=100)),
                ('lng', models.CharField(default=0.0, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Signalen',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datumtijd', models.DateTimeField(default=datetime.datetime(2018, 1, 4, 12, 5, 49, 648000))),
                ('text', models.CharField(default='', max_length=200)),
                ('signaal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='api.Signal')),
            ],
            options={
                'verbose_name_plural': 'Statussen',
            },
        ),
    ]
