# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rederij',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Rederijen',
            },
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'get_latest_by': 'datetime', 'verbose_name_plural': 'Signalen'},
        ),
        migrations.RemoveField(
            model_name='signal',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='omschrijving',
        ),
        migrations.RemoveField(
            model_name='status',
            name='datumtijd',
        ),
        migrations.RemoveField(
            model_name='status',
            name='signaal',
        ),
        migrations.AddField(
            model_name='signal',
            name='adres',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='afvalapi',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signal',
            name='coordinates',
            field=models.CharField(default='POINT (0.0 0.0)', max_length=100),
        ),
        migrations.AddField(
            model_name='signal',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='datetime_overlast',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='signal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='signal',
            name='main_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_cat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_cat_all',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_cat_all_prob',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_prob',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_sub_all',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_sub_all_prob',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_sub_cat',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='ml_sub_prob',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.CharField(default='api', max_length=15),
        ),
        migrations.AddField(
            model_name='signal',
            name='stadsdeel',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signal',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='signal',
            name='text',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signal',
            name='text_extra',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signal',
            name='waternet_naam_boot',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='waternet_rederij',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='signal',
            name='waternet_soort_boot',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee')], default=('Nee', 'Nee'), max_length=50),
        ),
        migrations.AddField(
            model_name='status',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='extern',
            field=models.BooleanField(default=False, help_text='Wel of niet status extern weergeven'),
        ),
        migrations.AddField(
            model_name='status',
            name='signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Signal', to='api.Signal'),
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Gemeld'), ('i', 'In afwachting op behandeling'), ('o', 'Opgelost')], default='m', help_text='Melding status', max_length=1),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
