# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180302_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
