# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180302_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
