# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_signal_latest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='latest_status',
        ),
        migrations.AddField(
            model_name='signal',
            name='last_status',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
