# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 11:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180305_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefoonnummer moet als het volgt worden ingediend:'+999999999'. Maximaal 15 karakters.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
