# Generated by Django 2.0.3 on 2018-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180306_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.AlterField(
            model_name='signal',
            name='datetime_overlast',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
