# Generated by Django 2.0.3 on 2018-03-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180315_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='datetime_overlast',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
