# Generated by Django 2.0.3 on 2018-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180315_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
