# Generated by Django 2.0.3 on 2018-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='datetime_overlast',
            field=models.DateTimeField(null=True),
        ),
    ]
