# Generated by Django 2.0.3 on 2018-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180321_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='signal',
            name='text_extra',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
