# Generated by Django 2.0.3 on 2018-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180321_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'get_latest_by': '-datetime', 'ordering': ['-datetime'], 'verbose_name_plural': 'Signalen'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'get_latest_by': 'datetime', 'verbose_name_plural': 'Statussen'},
        ),
    ]
